# ==================== 集群配置 ====================
# 换机器时，只改这个文件

# Master 节点内网 IP
k3s_master_ip: "172.26.18.227"

# Worker 节点内网 IP
k3s_worker_ip: "172.26.18.228"

# Harbor 配置
harbor_hostname: "{{ k3s_master_ip }}"
harbor_port: "8081"
harbor_version: "v2.10.0"
harbor_user: "admin"
harbor_password: "Harbor12345"

# 版本
k3s_version: "v1.36.4"
helm_version: "v3.14.4"
chart_version: "55.5.0"
keda_version: "2.20.2"

# 目录
project_dir: "/root/k3s-ai-platform"
