apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa-demo
  template:
    metadata:
      labels:
        app: hpa-demo
    spec:
      containers:
      - name: app
        image: 47.113.189.149:8081/library/hpa-demo:v3
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-demo
  labels:
    app: hpa-demo
spec:
  selector:
    app: hpa-demo
  ports:
  - name: http
    port: 8000
    targetPort: 8000
