apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hpa-demo-monitor
  namespace: default
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: hpa-demo
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
